### ISSUE TITLE
爬取百度搜索结果的时候报错ParseError: Invalid HTML content.

### ISSUE THREAD

**Issue by LiJinrun** [BaiduSpider/BaiduSpider#1]
![image](https://user-images.githubusercontent.com/49092533/95542791-53c09900-0a29-11eb-8721-584fe327f7cf.png)
请问这个是不是多次爬百度的，导致拒绝访问呢？

**Comment by py-wen-song** [comment]
> ![image](https://user-images.githubusercontent.com/49092533/95542791-53c09900-0a29-11eb-8721-584fe327f7cf.png)
> 请问这个是不是多次爬百度的，导致拒绝访问呢？

你如果还能打开百度的话，就不是被封IP的

**Comment by samzhangjy** [comment]
@JrLi-99 请给出报错的详细代码以及搜素词以便进一步确定issue原因，谢谢！

**Comment by loopyme** [comment]
当搜索不到结果的时候会出现ParseError

可以考虑使用`spider.search_web("dvyjftgsdjhdgbsauydgsauydg site:gov.cn")`来快速复现
