### ISSUE TITLE
[FEATURE]请求支持采集百度快照的地址

### ISSUE THREAD

**Issue by photkey** [BaiduSpider/BaiduSpider#101]
![image](https://user-images.githubusercontent.com/60434581/147848425-72d7883a-03b5-40f7-a2fc-0fe817f41064.png)
不知道这个功能是不是比较小众，百度快照对做SEO的很有用，希望能够支持。

**Comment by samzhangjy** [comment]
您好，此功能已在最新版（`1.0.2.1`）中添加，感谢您提出此需求。
