### ISSUE TITLE
[BUG] 无法正确过滤广告信息导致报错

### ISSUE THREAD

**Issue by ROIM1998** [BaiduSpider/BaiduSpider#106]
**描述该问题**
在使用search_baike()函数时，百度会给出语音助手、智能平台等相关广告链接，parser会将这些内容当作container的元素之一来处理，进而导致无法解析、输出NoneType等错误

**复现该问题**

from baiduspider import BaiduSpider
res = BaiduSpider().search_baike('甲骨文')

**预期结果**

预期返回正确的result对象

**实际结果**

输出报错：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zbw/.pyenv/versions/luke/lib/python3.9/site-packages/baiduspider/__init__.py", line 1101, in search_baike
    return BaikeResult._build_instance(result["results"], result["total"])
KeyError: 'total'

**系统**

- 操作系统: Ubuntu 18.04
- Python版本: 3.9.6

**其他描述**
解决办法：在parser的__init__.py文件的第780行后添加判断：
if res.select('.ad-footer'):
    continue
过滤掉所有的广告类型数据

新增：
另外在获取链接的代码处（第782行），应当增加判定URL为绝对路径还是相对路径，如果是相对路径才需要添加https://...的前缀，否则会获取到重复的完整链接前缀

**Comment by samzhangjy** [comment]
收到，正在修复

**Comment by samzhangjy** [comment]
bug fixed. 感谢您提出此问题。

**Comment by FHU-yezi** [comment]
感谢您给出了完整的复现流程和处理建议。
