### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zzy1036218147** [BaiduSpider/BaiduSpider#109]
设置代理后出现以下警告:

![image](https://user-images.githubusercontent.com/73581860/150090203-ff037a7a-8e2c-496d-9ba8-c9aedcb69f67.png)

![image](https://user-images.githubusercontent.com/73581860/150090446-1682d33e-317a-414f-b809-a1eb526bc629.png)

WARNING: An error occurred while executing function BaiduSpider.parse-web, which is currently ignored. However, the rest of the parsing process is still being executed normally. This is most likely an inner parse failure of BaiduSpider. For more details, please set the environment variable `DEBUG` to `1` to see the error trace and open up a new issue at https://github.com/BaiduSpider/BaiduSpider/issues/new?assignees=&labels=bug%2C+help+wanted&template=bug_report.md&title=%5BBUG%5D.

**Comment by FHU-yezi** [comment]
请设置环境变量 DEBUG = 1，然后发送错误堆栈信息，以便我们定位故障，感谢。

**Comment by admin-9ice** [comment]
![image](https://user-images.githubusercontent.com/58620182/153329644-8f25e7a8-82f7-41f5-a2f9-a9c0985c8726.png)
我也遇到了这个问题，但似乎设置环境变量并不生效。

**Comment by samzhangjy** [comment]
Closed due to a long time of inactivity.
