### ISSUE TITLE
[BUG]ParseError: Invalid HTML content.

### ISSUE THREAD

**Issue by Limourli-liu** [BaiduSpider/BaiduSpider#11]
**描述该问题**

一个对该问题的清晰的描述。
搜索'异度侵入'时报 ParseError: Invalid HTML content.

**复现该问题**

请提供能够复现该问题的代码或步骤。
t = BaiduSpider()
a = t.search_web(query='异度侵入', pn=1)

**预期结果**

一个对你想要的结果的清晰的描述。
搜素异度侵入的结果

**实际结果**

你实际得到的结果。

import requests...
---------------------------------------------------------------------------
ParseError                                Traceback (most recent call last)
e:\github\Aggregate-search\AgSearch\baidu.py in 
     81 if __name__ == '__main__':
     82     t = BaiduSpider()
---> 83     a = t.search_web(query='异度侵入', pn=1)
     84 

~\AppData\Local\Programs\Python\Python38\lib\site-packages\baiduspider\__init__.py in search_web(self, query, pn)
    180             error = err
    181         finally:
--> 182             self._handle_error(error)
    183         return {
    184             'results': results['results'],

~\AppData\Local\Programs\Python\Python38\lib\site-packages\baiduspider\_spider.py in _handle_error(self, err)
     69         else:
     70             error = UnknownError(str(err))
---> 71         raise error
     72 
     73     def __repr__(self) -> str:

~\AppData\Local\Programs\Python\Python38\lib\site-packages\baiduspider\__init__.py in search_web(self, query, pn)
    176             url = 'https://www.baidu.com/s?wd=%s&pn=%d' % (text, (pn - 1) * 10)
    177             content = self._get_response(url)
--> 178             results = self.parser.parse_web(content)
    179         except Exception as err:
    180             error = err

~\AppData\Local\Programs\Python\Python38\lib\site-packages\baiduspider\parser.py in parse_web(self, content)
     23         soup = BeautifulSoup(content, 'html.parser')
     24         if soup.find('div', id='content_left') is None:
---> 25             raise ParseError('Invalid HTML content.')
     26         # 获取搜索结果总数
     27         num = int(str(soup.find('span', class_='nums_text').text).strip(

ParseError: Invalid HTML content.

**系统**

- 操作系统: Win10x64例如：MacOS
- Python版本:3.8.2 例如：3.8

**其他描述**

一些关于问题的其他的描述。

**Comment by samzhangjy** [comment]
首先，感谢你提出issue！但是抱歉的是，我无法复现你的issue。请访问https://www.baidu.com/s?wd=异度侵入&pn=0，并右键查看源代码，将网页的源代码发送给我以进一步确定issue原因。

**Comment by Limourli-liu** [comment]
Baidu = BaiduSpider()
    Baidu.headers['Cache-Control'] =  'no-cache'
    Baidu.headers['Pragma'] =  'no-cache'
    Baidu.headers['Sec-Fetch-Dest'] =  'document'
    Baidu.headers['Sec-Fetch-Mode'] =  'navigate'
    Baidu.headers['Sec-Fetch-Site'] =  'none'
    Baidu.headers['Sec-Fetch-User'] =  '?1'
    Baidu.headers['Upgrade-Insecure-Requests'] =  '1'
    Baidu.headers['Cookie'] = 'BIDUPSID=....从浏览器获取的...A1598'
我补全headers后可以啦，感谢解答
