### ISSUE TITLE
[BUG]KeyError: 'total'

### ISSUE THREAD

**Issue by hayes-hou** [BaiduSpider/BaiduSpider#111]
**描述该问题**

Traceback (most recent call last):
  File "news.py", line 52, in <module>
    newslist = BaiduSpider().search_news(key, sort_by="time", pn=i, show="all", proxies=proxies).plain
  File "/usr/local/lib/python3.6/site-packages/baiduspider/__init__.py", line 770, in search_news
    pages = self._calc_pages(result["total"], self.RESULTS_PER_PAGE["news"])
KeyError: 'total'

**复现该问题**

请提供能够复现该问题的代码或步骤。

**预期结果**

一个对你想要的结果的清晰的描述。

**实际结果**

你实际得到的结果。

**系统**

- 操作系统: 例如：MacOS
- Python版本: 例如：3.8

**其他描述**

一些关于问题的其他的描述。

**Comment by samzhangjy** [comment]
请提供具体的程序代码以更好地定位错误原因。

**Comment by samzhangjy** [comment]
@wuhuanyan 您能给出一个复现代码嘛，谢谢

**Comment by wuhuanyan** [comment]
嗯旧版本的问题
