### ISSUE TITLE
[BUG] WARNING: An error occurred while executing function .

### ISSUE THREAD

**Issue by admin-9ice** [BaiduSpider/BaiduSpider#113]
**描述该问题**
在对“百度知道”页面进行爬取时，提示
WARNING: An error occurred while executing function ., which is currently ignored. However, the rest of the parsing process is still being executed normally. This is most likely an inner parse failure of BaiduSpider. For more details, please set the environment variable `DEBUG` to `1` to see the error trace and open up a new issue at https://github.com/BaiduSpider/BaiduSpider/issues/new?assignees=&labels=bug%2C+help+wanted&template=bug_report.md&title=%5BBUG%5D.

**复现该问题**
单独运行此段代码就会报出上述警告
![image](https://user-images.githubusercontent.com/58620182/153344798-fe58b787-7185-4848-940f-a1f66811e381.png)

**预期结果**
结果应为类似于 “12345 四叶草 https://xxx.xxx.xxx.....” 的输出

**实际结果**
WARNING: An error occurred while executing function ., which is currently ignored. However, the rest of the parsing process is still being executed normally. This is most likely an inner parse failure of BaiduSpider. For more details, please set the environment variable `DEBUG` to `1` to see the error trace and open up a new issue at https://github.com/BaiduSpider/BaiduSpider/issues/new?assignees=&labels=bug%2C+help+wanted&template=bug_report.md&title=%5BBUG%5D.

**系统**
- 操作系统: Windows 10
- Python版本: 3.8

**其他描述**
在文档中我找到了 环境变量中设置DEBUG=1然后再查看堆栈信息检查问题的解决方法，但似乎没有效果。
![image](https://user-images.githubusercontent.com/58620182/153345276-af9b7e24-9e35-4d4b-ae5e-dd4d431ee32c.png)

**Comment by admin-9ice** [comment]
**补充**
对于是否是由于 “爬取过于频繁导致此警告”
在写代码逻辑的初期，并没有出现此警告，但当我大概for了20~30次时，我认为我的代码逻辑ok了，就先停掉了它。
但当我再次使用此段代码时，就出现了这个警告，并且在停止运行爬虫数小时后仍未恢复。
此间手动使用浏览器访问正常。

**Comment by samzhangjy** [comment]
正在检查 Issue 原因。

**Comment by samzhangjy** [comment]
@admin-9ice 请提供相关搜索词以完整复现问题，谢谢。

**Comment by admin-9ice** [comment]
有创血压监测
血府
低氧血症的诊断标准
牙周膜息肉
烈士抚恤金发放标准
vap预防措施
1151压力变送器
安全帽的作用
阀门手轮
白炽灯功率

**Comment by samzhangjy** [comment]
Issue fixed in the latest release.
