### ISSUE TITLE
[BUG] api的结果和浏览器上结果不同

### ISSUE THREAD

**Issue by heyitao** [BaiduSpider/BaiduSpider#114]
**描述该问题**

安装了最新的版本

执行：
BaiduSpider().search_web("微笑").plain

得到的结果只有"related" 和"baike" 两种类型的结果

实际浏览器搜索不止这些结果

**系统**

- 操作系统: win10
- iDE：pycharm
- Python版本: 例如：3.7

**其他描述**

一些关于问题的其他的描述。

**Comment by heyitao** [comment]
可能是频率的问题，过一会儿又好了

**Comment by heyitao** [comment]
今天看了一些，不是ip被封的问题，是parser的问题（from baiduspider.parser import Parser），请求得到的html信息是全的，parser出来的结果少了很多，应该是百度改了格式？

**Comment by samzhangjy** [comment]
已经修复了，现在最新版应该可以了
