### ISSUE TITLE
你好，我这边无法获取到普通搜索的内容

### ISSUE THREAD

**Issue by boddy** [BaiduSpider/BaiduSpider#115]
macos
python3.10
v1.0.2.6
谢谢开发者

**Comment by boddy** [comment]
v1.0.2.6

**Comment by samzhangjy** [comment]
请提供更详细的 Issue 信息，包括程序代码和运行报错的截图。
如果不方便提供代码也请注明搜索词，谢谢。

**Comment by boddy** [comment]
我这边是按照代码里面的操作提示，主动传了cookie，如果不传cookie，则能返回普通搜索及百科等数据
查看了下代码的类名称为
`<div class="result c-container new-pmd" id="2" srcid="1599"`

**Comment by samzhangjy** [comment]
那有可能是 cookie 传错了，请按照 [文档](https://baiduspider.github.io/guide/index.html#%E8%AE%BE%E7%BD%AECookie) 传递 cookie 。
