### ISSUE TITLE
运行示例代码报错，BaiduSpider无法导入[BUG]

### ISSUE THREAD

**Issue by 17186765070** [BaiduSpider/BaiduSpider#117]
![image](https://user-images.githubusercontent.com/84702815/155441265-b7b14e27-9578-4c52-b406-5e9620ebbe13.png)

**Comment by 17186765070** [comment]
python3.7
win10

**Comment by samzhangjy** [comment]
请检查是否安装 BaiduSpider 。如果仍无法正常运行，请移步至 Discussions 讨论。
