### ISSUE TITLE
[BUG]异常没有”total“key

### ISSUE THREAD

**Issue by glacierck** [BaiduSpider/BaiduSpider#119]
**描述该问题**

当查询结果为空时异常，错误读取不存在的"total"属性。

经分析是152行中的self.EMPTY = {"results": [], "pages": 0} 中没有”total“定义。

**复现该问题**

请提供能够复现该问题的代码或步骤。

**预期结果**

图片查询api 查询 ”2021 GDP filetype:xls“，返回空数组。

**实际结果**

异常报错。

**系统**

- 操作系统:  MacOS
- Python版本: 3.7

**其他描述**

一些关于问题的其他的描述。

**Comment by samzhangjy** [comment]
Closed due to the merge of pull request #123 .
