### ISSUE TITLE
[BUG]install error

### ISSUE THREAD

**Issue by wekylin** [BaiduSpider/BaiduSpider#12]
**描述该问题**
python setup.py install
.. ...
Installed d:\dev\python\lib\site-packages\baiduspider-0.0.6-py3.8.egg
Processing dependencies for BaiduSpider==0.0.6
Searching for htmlmin
Reading https://pypi.org/simple/htmlmin/
Download error on https://pypi.org/simple/htmlmin/: [Errno 2] No such file or directory -- Some packages may not be found!
Couldn't find index page for 'htmlmin' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [Errno 2] No such file or directory -- Some packages may not be found!
No local packages or working download links found for htmlmin
error: Could not find suitable distribution for Requirement.parse('htmlmin')

**复现该问题**
python 3.8.7
python setup.py install

请提供能够复现该问题的代码或步骤。
windows 10 + python 3.8.7
python setup.py install

**预期结果**

安装成功

**实际结果**

安装错误

**系统**
- Windows 10 Pro 1909
- Python版本: 例如：3.8.7

**其他描述**

一些关于问题的其他的描述。

**Comment by samzhangjy** [comment]
很抱歉，我无法复现该问题。但是从报错中来看，这不是有关BaiduSpider的错误。请问您使用的`pip`是什么版本？

**Comment by Edgaraaa** [comment]
表示同样问题，之后自己访问了一下，发现是被百度ban了

**Comment by samzhangjy** [comment]
由于无法复现此问题且无人回复，关闭此issue。如果还有问题，请reopen此issue。
