### ISSUE TITLE
[BUG]搜索结果（图片）结果数据量少时的total值提取错误。

### ISSUE THREAD

**Issue by glacierck** [BaiduSpider/BaiduSpider#120]
**描述该问题**

当搜索结果为三位数（测试197）时百度将不再使用”找到相关图片约xxxxx张“这样的字符模板，而是”找到相关图片X张
“,没有关机字”约“，这导致程序异常直接跳出，建议像total这样的字段支持抽取失败，直接给个-1区别于无结果即可。

**复现该问题**

在图片查询中输入”title:表 2021年GDP“

**预期结果**

返回列表。

**实际结果**

程序异常。

**系统**

- 操作系统: 例如：MacOS
- Python版本: 例如：3.7

**其他描述**

一些关于问题的其他的描述。

**Comment by glacierck** [comment]
已提交修改

**Comment by samzhangjy** [comment]
Duplicate of #121 .
