### ISSUE TITLE
[BUG]search_web返回值为空，其余方法正常

### ISSUE THREAD

**Issue by zengaorong** [BaiduSpider/BaiduSpider#128]
spider = BaiduSpider()

# 搜索网页
pprint(spider.search_web(query="pyhton").plain)
pprint(spider.search_news(query="python", pn=2).plain)

第一个方法返回空数组

**Comment by glces** [comment]
遇到同样的问题

**Comment by zengaorong** [comment]
谢谢回复了问题，只是我按照上述进行了修改，未解决问题，返回还是空的。

**Comment by glces** [comment]
> 谢谢回复了问题，只是我按照上述进行了修改，未解决问题，返回还是空的。
baiduspider/init  第441行后加print(content)看看是不是被限制了。最开始我我是输出了这里看到提示百度安全验证，后来用了代理才OK

**Comment by zengaorong** [comment]
嗯嗯是的，我也调试了下，要过百度安全验证，谢谢了

**Comment by sauceplus** [comment]
你好，我也是发生了安全验证，这个要怎么通过呢？谢谢
