### ISSUE TITLE
[FEATURE]我想要一个能判断 网址内页是否被百度收录的接口

### ISSUE THREAD

**Issue by yongliu1992** [BaiduSpider/BaiduSpider#13]
**你的功能请求是跟一个问题有关吗？请描述。**
无

**你想要什么**

程序能提供一个http接口，参数为网址，程序来判断是否有被收录， 还有 需要防范百度的反爬

**你想过的解决方案**

flask 提供http服务，从ip代理池中获取到ip，代理 进行查询
**其他描述**

无

**Comment by AdminWhaleFall** [comment]
## GitHub上同类型的项目
> https://github.com/HW140701/SearchEngineRecordQueryAPI
## 后期考虑集成在baiduspider

**Comment by yongliu1992** [comment]
> ## GitHub上同类型的项目
> > https://github.com/HW140701/SearchEngineRecordQueryAPI
> 
> ## 后期考虑集成在baiduspider

这个项目我用过，数量多了不行，反爬机制不行，我自己后来是通过 selenium  + chrome完成的

**Comment by samzhangjy** [comment]
目前百度的反爬措施还是很完备的，比较难处理百度的验证，因为手动搜索100次以上也会出现验证页面。目前的解决方案是使用代理池轮换，后期也会考虑绕开百度验证。

**Comment by samzhangjy** [comment]
如果你有更好的解决方案，欢迎来提交PR😉

**Comment by yongliu1992** [comment]
有个方案就是 先登录上去，然后去搜索 就会好很多。
