### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HaiGe120** [BaiduSpider/BaiduSpider#14]
When running he demo.py as it presented at readme.md

```
python3 x.py
```
also tried python x.py didn't work

outputs are like

Traceback (most recent call last):
  File "/root/tmp.py", line 1, in <module>
    from baiduspider import BaiduSpider
  File "/usr/local/lib/python3.9/site-packages/baiduspider/__init__.py", line 19, in <module>
    from baiduspider.parser.parser import Parser
ModuleNotFoundError: No module named 'baiduspider.parser'

Python3.9 in debian10 with zsh, package path added

**Comment by samzhangjy** [comment]
Thank you for submitting this issue. We confirmed this issue and are building a hot-fix version. Sorry for the inconvenience.

**Comment by samzhangjy** [comment]
Issue fixed. Please reinstall BaiduSpider to the latest version (v0.1.6) and try again. Sorry for the inconvenience.

**Comment by samzhangjy** [comment]
If you have any questions, feel free to re-open the issue.

**Comment by HaiGe120** [comment]
> If you have any questions, feel free to re-open the issue.



> Issue fixed. Please reinstall BaiduSpider to the latest version (v0.1.6) and try again. Sorry for the inconvenience.

appreciate the speedy support ❤
