### ISSUE TITLE
[BUG] UnboundLocalError("local variable 'results' referenced before assignment")

### ISSUE THREAD

**Issue by Nickel-Nie** [BaiduSpider/BaiduSpider#161]
**描述该问题**

在多线程情况下，每个线程一个BaiduSpider对象，等待一段时间后会出现UnboundLocalError问题。
单线程情况下没有出现这种情况

**复现该问题**

多线程情况下
resultNum = spider.search_web(query=xxxx, time=(datetime(2012, 1, 1), datetime(2012, 12, 31))).total

**预期结果**

能给出一个解决方案。

**实际结果**

暂无

**系统**

- 操作系统: 例如：Windows11
- Python版本: 例如：3.8

**其他描述**

一些关于问题的其他的描述。

**Comment by MusicOfWind** [comment]
> **描述该问题**
> 
> 在多线程情况下，每个线程一个BaiduSpider对象，等待一段时间后会出现UnboundLocalError问题。 单线程情况下没有出现这种情况
> 
> **复现该问题**
> 
> 多线程情况下 resultNum = spider.search_web(query=xxxx, time=(datetime(2012, 1, 1), datetime(2012, 12, 31))).total
> 
> **预期结果**
> 
> 能给出一个解决方案。
> 
> **实际结果**
> 
> 暂无
> 
> **系统**
> 
> * 操作系统: 例如：Windows11
> * Python版本: 例如：3.8
> 
> **其他描述**
> 
> 一些关于问题的其他的描述。

怎么解决的老哥
