### ISSUE TITLE
[BUG] exception,,e=local variable 'result' referenced before assignment

### ISSUE THREAD

**Issue by coderguang** [BaiduSpider/BaiduSpider#18]
__init__.py   图片搜索  search_pic  中出现

**Comment by samzhangjy** [comment]
首先，感谢您提出issue。遗憾的是，我无法复现该问题。请问您使用的BaiduSpider版本是否是最新版本（`v0.1.10`）？如果不是，请升级到最新版本并重试。如果还出现该报错，请提供您使用的搜索词以进一步分析报错原因。谢谢！

**Comment by samzhangjy** [comment]
经过测试，该问题可能并非是BaidupSpider内部错误。在2021.3.19，该issue已经无法复现，可能是因为百度页面调整所致。如果仍然存在问题，请重新开启issue并说明细节。谢谢！
