### ISSUE TITLE
循环抓取时报错及中文报错

### ISSUE THREAD

**Issue by jack1545** [BaiduSpider/BaiduSpider#20]
问题一：循环抓取

`for page in range(2,21):
    try:
        pprint(spider.search_zhidao(query=query,pn=page))
    except Exception as Error:
        print(Error)
`

错误如下

`WARNING: An error occurred while executing function ., which is currently ignored. However, the rest of the parsing process is still being executed normally. This is most likely an inner parse failure of BaiduSpider. For more details, please set the environment variable `DEBUG` to `1` to see the error trace and open up a new issue at https://github.com/BaiduSpider/BaiduSpider/issues/new?assignees=&labels=bug%2C+help+wanted&template=bug_report.md&title=%5BBUG%5D.
Traceback (most recent call last):
  File "D:/Project/upstar/SpiderBaidu.py", line 11, in <module>
    pprint(spider.search_zhidao(query=query,pn=page))
  File "D:\Progarming\PythonEnvs\upstar-e7ASbuYY\lib\site-packages\baiduspider\__init__.py", line 386, in search_zhidao
    return {"results": result["results"], "total": result["pages"]}
UnboundLocalError: local variable 'result' referenced before assignment
`
加入Try可以解决这个问题。但不能解决根源问题。

问题二、使用中文时报错，需要将中文转为uincode才可以使用

`
pprint(spider.search_zhidao(query=u‘游戏’))

pprint(spider.search_zhidao(query='\u6e38\u620f'))
`

**Comment by jack1545** [comment]
中文的问题通过format重构url解决了 url = "https://zhidao.baidu.com/search?lm=0&rn=10&fr=search&pn={0}&word={1}".format((pn - 1 * 10),query)

**Comment by samzhangjy** [comment]
>问题一：循环抓取
>
>```python
>for page in range(2,21): try: pprint(spider.search_zhidao(query=query,pn=page)) except Exception as Error: print(Error)
>```

此issue正在被修复。感谢提出！

>问题二、使用中文时报错，需要将中文转为uincode才可以使用
>
>```python
>pprint(spider.search_zhidao(query=u‘游戏’))
>
>pprint(spider.search_zhidao(query='\u6e38\u620f'))
>```

很抱歉，我无法复现你的这个issue。
