### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by 875279177** [BaiduSpider/BaiduSpider#21]
**你的功能请求是跟一个问题有关吗？请描述。**
没有广告标识的信息
你的问题的清晰的描述。
如搜索关键字 旅游 在最上方的的几条带有广告字样的是检索不到的
**你想要什么**
是否能把用户看到的真实信息返回
对你想要的功能的尽量清晰的描述。
所见即所得
**你想过的解决方案**

简单描述一下你想用的解决方案。

**其他描述**

其他关于该功能请求的描述。

**Comment by samzhangjy** [comment]
很抱歉，BaiduSpider目前暂不考虑获取广告信息。如果您需要，请自行改编现有代码以实现您所需要的需求或查找同类项目。十分抱歉。
