### ISSUE TITLE
[FEATURE]请问可以实现直接返回真实URL吗？

### ISSUE THREAD

**Issue by zyoung1212** [BaiduSpider/BaiduSpider#22]
请问可以实现直接返回真实URL吗？

**Comment by samzhangjy** [comment]
您好。我其实很久之前在项目初期就考虑过这个问题，正如你能在代码里看到的，我最初使用的是循环访问获取真实URL。但是，这种做法效率太低。后来我又查看了百度的JS，发现这个URL是用哈希生成的，salt还暂未找到。以我目前的技术水平可能无法逆向解析URL，如果您有想法也请指教！

**Comment by zyoung1212** [comment]
> 您好。我其实很久之前在项目初期就考虑过这个问题，正如你能在代码里看到的，我最初使用的是循环访问获取真实URL。但是，这种做法效率太低。后来我又查看了百度的JS，发现这个URL是用哈希生成的，salt还暂未找到。以我目前的技术水平可能无法逆向解析URL，如果您有想法也请指教！

感谢您的回复。我是之前用过一个chrome的插件，该插件能够屏蔽百度的重定向功能。
不知道是否能够参考呢？https://github.com/langren1353/GM_script

**Comment by samzhangjy** [comment]
> > 您好。我其实很久之前在项目初期就考虑过这个问题，正如你能在代码里看到的，我最初使用的是循环访问获取真实URL。但是，这种做法效率太低。后来我又查看了百度的JS，发现这个URL是用哈希生成的，salt还暂未找到。以我目前的技术水平可能无法逆向解析URL，如果您有想法也请指教！
> 
> 感谢您的回复。我是之前用过一个chrome的插件，该插件能够屏蔽百度的重定向功能。
> 不知道是否能够参考呢？https://github.com/langren1353/GM_script

谢谢。我正在与该项目作者取得联系。若作者同意，我将集成该项目算法至BaiduSpider。

**Comment by samzhangjy** [comment]
您好。我已经与该项目作者取得联系，该作者表示，他所使用的基本算法也是循环访问。但是，这种方法对于爬虫效率过低。我也会尽我所能寻找可能的解密算法。也期待您的贡献。

**Comment by samzhangjy** [comment]
抱歉。我曾多次研究过这个问题，但是都无法实现。如果您有更好的建议，欢迎提出。本issue已被关闭，若有新建议请重新开启。

**Comment by zyoung1212** [comment]
> 抱歉。我曾多次研究过这个问题，但是都无法实现。如果您有更好的建议，欢迎提出。本issue已被关闭，若有新建议请重新开启。

收到！非常感谢您的尝试。
