### ISSUE TITLE
[FEATURE] 不能抓取音乐卡片

### ISSUE THREAD

**Issue by wwt1991wwz** [BaiduSpider/BaiduSpider#26]
**描述该问题**

不能抓取音乐卡片

**复现该问题**

请播放踏山河

**预期结果**

res_type=music

**实际结果**

none

**系统**

- 操作系统: 例如：MacOS
- Python版本: 例如：3.8

**其他描述**

一些关于问题的其他的描述。

**Comment by samzhangjy** [comment]
您好。感谢提出该功能。当功能被添加后我将通知您。谢谢！

**Comment by samzhangjy** [comment]
此需求请求已经在[即将发布的V1.0.0版本](https://github.com/BaiduSpider/BaiduSpider/issues/29)中加入，敬请期待。

**Comment by samzhangjy** [comment]
BaiduSpider v1.0 发布，请更新BaiduSpider到最新版本！
