### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ZenoLeee** [BaiduSpider/BaiduSpider#27]
**描述该问题**

在多次请求(多线程)的情况下会出现
WARNING: An error occurred while parsing the tieba subcomponent of BaiduSpider.parse_web, which is currently ignored. However, the rest of the parsing process is still being executed normally. This is most likely an inner parse failure of BaiduSpider.

**复现该问题**

`
# -*- coding: utf-8 -*-
from baiduspider import BaiduSpider
import threading
import queue
import xlsxwriter

class MyThread(threading.Thread):
    def __init__(self, page):
        super().__init__()
        self.page = page

    def run(self) -> None:
        while True:
            if self.page.empty():
                break
            self.get_info()

    def get_info(self):
        page = self.page.get()
        spider = BaiduSpider()
        response = spider.search_web(query="欧阳靖", pn=page)
        data = []
        for result in response["results"]:
            url = result.get("url")
            if result.get("url"):
                data.append(result.get("url"))
                continue
            result_type = result.get("type")
            # 百科处理
            if result.get("result") and result_type != 'total':
                data.append(result.get("result").get("url"))
                continue
            # 其他处理
            if result_type != 'total' and result_type != "related":
                for i in result.get("results"):
                    data.append(i.get('url'))
        if len(excel_data) % 1000 == 0:
            excel_data.append([])
        excel_data.append(data)
        print(page)

excel_data = []

# 启动线程队列
work_queue = queue.Queue()
# 传参
for i in range(1, 300):
    work_queue.put(i)

threads = []
for j in range(50):
    thread_do = MyThread(work_queue)
    thread_do.start()
    threads.append(thread_do)

for k in threads:
    k.join()

def to_excel():
    column = ['链接']  # 列表对应每列的列名
    test = pd.DataFrame(columns=column, data=self.data)
    path = r'./1.xlsx'
    test.to_excel(path, engine='xlsxwriter')  # 如果生成excel，可以用to_excel
`

**实际结果**

起码不报错吧, 也不知道是什么

**系统**

- 操作系统: 例如：MacOS
- Python版本: 例如：3.8

**Comment by samzhangjy** [comment]
首先，感谢你提出issue。但是，我无法复现这个issue - 我尝试使用BaiduSpider最新版（0.1.13），搜索“欧阳靖”并未出现warning。另外，此警告是BaiduSpider内部解析出现错误自动处理的机制，解析报错后BaiduSpider会自动发出警告，但是剩余的解析仍被正常执行。请更新到最新版本后重试并提供详细报错页面/页码。
