### ISSUE TITLE
[BUG]百度搜索超过100次会出现安全验证，不知道是否是什么问题，这个是否可以解决一下

### ISSUE THREAD

**Issue by sankeyou123** [BaiduSpider/BaiduSpider#3]
在搜索过程中会出现百度安全验证，不知道百度是什么防御机制

**Comment by sankeyou123** [comment]
手动点击搜索超过100次也会出现验证，可以手动尝试一下，但是换了浏览器又可以继续搜搜，不知道是怎么防御的

**Comment by samzhangjy** [comment]
这个可能是百度记录浏览器指纹来识别的，爬虫中最常用的办法是更换IP地址来预防该现象

**Comment by b1ueb0y** [comment]
@samzhangjy 更换头也没用，只要是高并发马上就百度安全验证了

**Comment by lyzq** [comment]
这个close掉了，是已经解决了么？
