### ISSUE TITLE
[BUG]百度人机验证码

### ISSUE THREAD

**Issue by insoxin** [BaiduSpider/BaiduSpider#30]
`root@i ~]# curl https://www.baidu.com/s?ie=utf8&oe=utf8&wd=curl
[1] 14570
[2] 14571
[root@i ~]# <a href="https://wappass.baidu.com/static/captcha/tuxing.html?&amp;ak=c27bbc89afca0463650ac9bde68ebe06&amp;backurl=https%3A%2F%2Fwww.baidu.com%2Fs%3Fie%3Dutf8&amp;logid=8871806922390316314&amp;signature=63c42cdf040b51fd402cb53e7db10eaf&amp;timestamp=1618224779">Found</a>.
`

过多爬取就这样了,旋转验证码

**Comment by samzhangjy** [comment]
您好。目前我还没有对于验证码较好的处理办法。我目前唯一的解决方案就是使用IP代理池来循环调用IP，变向的回避验证码问题。如果您有更好的处理办法，欢迎提出！

**Comment by insoxin** [comment]
> 您好。目前我还没有对于验证码较好的处理办法。我目前唯一的解决方案就是使用IP代理池来循环调用IP，变向的回避验证码问题。如果您有更好的处理办法，欢迎提出！

用百度云自家的服务器,会有加成吗

**Comment by samzhangjy** [comment]
> > 您好。目前我还没有对于验证码较好的处理办法。我目前唯一的解决方案就是使用IP代理池来循环调用IP，变向的回避验证码问题。如果您有更好的处理办法，欢迎提出！
> 
> 用百度云自家的服务器,会有加成吗

这个……不太清楚……但是我个人认为大概率不会
