### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xzltc** [BaiduSpider/BaiduSpider#33]
**描述该问题**

调用search_web添加屏蔽搜索结果前后result数量没有区别，type还是显示为'total'

**复现该问题**

exclude = ['news', 'video', 'baike', 'tieba', 'blog', 'gitee', 'related', 'calc']
spider.search_web(query='中国银行', time=(datetime(2011, 1, 1), datetime(2012, 1, 1)), exclude=exclude) #结果为48600000
spider.search_web(query='中国银行', time=(datetime(2011, 1, 1), datetime(2012, 1, 1))) #result数量相同

**系统**

- 操作系统: MacOS
- Python版本: 3.8

**Comment by samzhangjy** [comment]
额……BaiduSpider的结果数量不在BaiduSpider的组件屏蔽范围内，而且对于解析速度没有太大的影响。另外，结果数量是由百度搜索栏下方的信息进行抓取，而非BaiduSpider亲自统计的：
![image.png](https://i.loli.net/2021/07/02/ze5Z9ACcmnDFGEb.png)
该结果本身就是大致数量，因此我并没有把屏蔽掉的搜索结果数量减去（大部分还是普通的搜索结果嘛）。

如果您有其他问题，欢迎提出！
