### ISSUE TITLE
[BUG]search_news返回结果为空

### ISSUE THREAD

**Issue by qwertylx** [BaiduSpider/BaiduSpider#34]
**描述该问题**

search_news返回结果为空

**复现该问题**

from baiduspider import BaiduSpider
from pprint import pprint
spider = BaiduSpider()
pprint(spider.search_news(query='python'))

**实际结果**

WARNING: An error occurred while executing function ., which is currently ignored. However, the rest of the parsing process is still being executed normally. This is most likely an inner parse failure of BaiduSpider. For more details, please set the environment variable `DEBUG` to `1` to see the error trace and open up a new issue at https://github.com/BaiduSpider/BaiduSpider/issues/new?assignees=&labels=bug%2C+help+wanted&template=bug_report.md&title=%5BBUG%5D.
{'results': [], 'total': 0}

**系统**

- 操作系统: Windows
- Python版本: 3.7

**其他描述**

1. 换其他关键词尝试，total的结果可能不为0，但results结果仍然为空
2. serach_web返回结果不为空，与主页示例代码一致，但是仍然有如下warning：
WARNING: An error occurred while parsing the aike subcomponent of BaiduSpider.parse_web, which is currently ignored. However, the rest of the parsing process is still being executed normally. This is most likely an inner parse failure of BaiduSpider. For more details, please set the environment variable `DEBUG` to `1` to see the error trace and open up a new issue at https://github.com/BaiduSpider/BaiduSpider/issues/new?assignees=&labels=bug%2C+help+wanted&template=bug_report.md&title=%5BBUG%5D.

**Comment by samzhangjy** [comment]
您好。该问题已经在最新的开发版中修复，请安装开发版本（`dev`分支）然后重试。谢谢！

另：开发版本安装方法：

1. clone GitHub repo：`git@github.com:BaiduSpider/BaiduSpider.git`
2. 切换到`dev`分支：`git checkout dev`
3. 手动安装BaiduSpider：`python setup.py install`

开发版本中有些新功能可能尚未出现在文档中，如返回结果类，如果不想使用该功能可以直接在搜索函数返回值后面添加`.plain`即可。

**Comment by qwertylx** [comment]
> 您好。该问题已经在最新的开发版中修复，请安装开发版本（`dev`分支）然后重试。谢谢！
> 
> 另：开发版本安装方法：
> 
> 1. clone GitHub repo：`git@github.com:BaiduSpider/BaiduSpider.git`
> 2. 切换到`dev`分支：`git checkout dev`
> 3. 手动安装BaiduSpider：`python setup.py install`
> 
> 开发版本中有些新功能可能尚未出现在文档中，如返回结果类，如果不想使用该功能可以直接在搜索函数返回值后面添加`.plain`即可。

感谢回复。按照步骤安装后，执行同样的代码出现了另外的error，如下：

Traceback (most recent call last):
  File "xxxxxxxxxxx.py", line 1, in <module>
    from baiduspider import BaiduSpider
  File "E:\Anaconda\lib\site-packages\baiduspider-0.1.13-py3.7.egg\baiduspider\__init__.py", line 20, in <module>
    from baiduspider.models.web import WebResult
  File "E:\Anaconda\lib\site-packages\baiduspider-0.1.13-py3.7.egg\baiduspider\models\web.py", line 8, in <module>
    from baiduspider.models.typings.typings_web import *
ModuleNotFoundError: No module named 'baiduspider.models.typings'

将项目中的typing文件夹复制到‘E:\Anaconda\lib\site-packages\baiduspider-0.1.13-py3.7.egg\baiduspider\models\'路径下即可解决。

另：关于dev版本的结果类问题，‘pages‘是否等价于master版本中的‘total’属性？若不是，怎样在dev版本中获取搜索结果的最大页码？

**Comment by samzhangjy** [comment]
> > 您好。该问题已经在最新的开发版中修复，请安装开发版本（`dev`分支）然后重试。谢谢！
> > 另：开发版本安装方法：
> > 
> > 1. clone GitHub repo：`git@github.com:BaiduSpider/BaiduSpider.git`
> > 2. 切换到`dev`分支：`git checkout dev`
> > 3. 手动安装BaiduSpider：`python setup.py install`
> > 
> > 开发版本中有些新功能可能尚未出现在文档中，如返回结果类，如果不想使用该功能可以直接在搜索函数返回值后面添加`.plain`即可。
> 
> 感谢回复。按照步骤安装后，执行同样的代码出现了另外的error，如下：
> 
> Traceback (most recent call last):
> File "xxxxxxxxxxx.py", line 1, in
> from baiduspider import BaiduSpider
> File "E:\Anaconda\lib\site-packages\baiduspider-0.1.13-py3.7.egg\baiduspider__init__.py", line 20, in
> from baiduspider.models.web import WebResult
> File "E:\Anaconda\lib\site-packages\baiduspider-0.1.13-py3.7.egg\baiduspider\models\web.py", line 8, in
> from baiduspider.models.typings.typings_web import *
> ModuleNotFoundError: No module named 'baiduspider.models.typings'
> 
> 将项目中的typing文件夹复制到‘E:\Anaconda\lib\site-packages\baiduspider-0.1.13-py3.7.egg\baiduspider\models'路径下即可解决。
> 
> 另：关于dev版本的结果类问题，‘pages‘是否等价于master版本中的‘total’属性？若不是，怎样在dev版本中获取搜索结果的最大页码？

抱歉，我正在调查这个问题的原因，修复后会通知您。

是的，`dev`分支中的`pages`属性等价于`master`分支中的`total`属性，只不过更改了名字而已。

谢谢！

**Comment by qwertylx** [comment]
> > > 您好。该问题已经在最新的开发版中修复，请安装开发版本（`dev`分支）然后重试。谢谢！
> > > 另：开发版本安装方法：
> > > 
> > > 1. clone GitHub repo：`git@github.com:BaiduSpider/BaiduSpider.git`
> > > 2. 切换到`dev`分支：`git checkout dev`
> > > 3. 手动安装BaiduSpider：`python setup.py install`
> > > 
> > > 开发版本中有些新功能可能尚未出现在文档中，如返回结果类，如果不想使用该功能可以直接在搜索函数返回值后面添加`.plain`即可。
> > 
> > 
> > 感谢回复。按照步骤安装后，执行同样的代码出现了另外的error，如下：
> > Traceback (most recent call last):
> > File "xxxxxxxxxxx.py", line 1, in
> > from baiduspider import BaiduSpider
> > File "E:\Anaconda\lib\site-packages\baiduspider-0.1.13-py3.7.egg\baiduspider__init__.py", line 20, in
> > from baiduspider.models.web import WebResult
> > File "E:\Anaconda\lib\site-packages\baiduspider-0.1.13-py3.7.egg\baiduspider\models\web.py", line 8, in
> > from baiduspider.models.typings.typings_web import *
> > ModuleNotFoundError: No module named 'baiduspider.models.typings'
> > 将项目中的typing文件夹复制到‘E:\Anaconda\lib\site-packages\baiduspider-0.1.13-py3.7.egg\baiduspider\models'路径下即可解决。
> > 另：关于dev版本的结果类问题，‘pages‘是否等价于master版本中的‘total’属性？若不是，怎样在dev版本中获取搜索结果的最大页码？
> 
> 抱歉，我正在调查这个问题的原因，修复后会通知您。
> 
> 是的，`dev`分支中的`pages`属性等价于`master`分支中的`total`属性，只不过更改了名字而已。
> 
> 谢谢！

感谢回复。One more question: 根据百度搜索的规则，关于pages的值，是否可以这样理解：pn值设置不同，则返回的pages值不同？还是说pages的值始终等于搜索结果可以到达的最大页码数？

**Comment by samzhangjy** [comment]
> > > > 您好。该问题已经在最新的开发版中修复，请安装开发版本（`dev`分支）然后重试。谢谢！
> > > > 另：开发版本安装方法：
> > > > 
> > > > 1. clone GitHub repo：`git@github.com:BaiduSpider/BaiduSpider.git`
> > > > 2. 切换到`dev`分支：`git checkout dev`
> > > > 3. 手动安装BaiduSpider：`python setup.py install`
> > > > 
> > > > 开发版本中有些新功能可能尚未出现在文档中，如返回结果类，如果不想使用该功能可以直接在搜索函数返回值后面添加`.plain`即可。
> > > 
> > > 
> > > 感谢回复。按照步骤安装后，执行同样的代码出现了另外的error，如下：
> > > Traceback (most recent call last):
> > > File "xxxxxxxxxxx.py", line 1, in
> > > from baiduspider import BaiduSpider
> > > File "E:\Anaconda\lib\site-packages\baiduspider-0.1.13-py3.7.egg\baiduspider__init__.py", line 20, in
> > > from baiduspider.models.web import WebResult
> > > File "E:\Anaconda\lib\site-packages\baiduspider-0.1.13-py3.7.egg\baiduspider\models\web.py", line 8, in
> > > from baiduspider.models.typings.typings_web import *
> > > ModuleNotFoundError: No module named 'baiduspider.models.typings'
> > > 将项目中的typing文件夹复制到‘E:\Anaconda\lib\site-packages\baiduspider-0.1.13-py3.7.egg\baiduspider\models'路径下即可解决。
> > > 另：关于dev版本的结果类问题，‘pages‘是否等价于master版本中的‘total’属性？若不是，怎样在dev版本中获取搜索结果的最大页码？
> > 
> > 
> > 抱歉，我正在调查这个问题的原因，修复后会通知您。
> > 是的，`dev`分支中的`pages`属性等价于`master`分支中的`total`属性，只不过更改了名字而已。
> > 谢谢！
> 
> 感谢回复。One more question: 根据百度搜索的规则，关于pages的值，是否可以这样理解：pn值设置不同，则返回的pages值不同？还是说pages的值始终等于搜索结果可以到达的最大页码数？

`pages`参数的值是通过获取百度搜索底部分页栏来进行爬取的，因此展示的并不是实际的最大页码。详见：<https://baiduspider.github.io/native/#total>

另：如果您想了解更多BaiduSpider方面的问题，请加我QQ：2947602769。

**Comment by samzhangjy** [comment]
我已经提交了一个最新的commit并修复了这个问题。请尝试再次clone本repo后手动安装BaiduSpider并测试能否使用。谢谢！
