### ISSUE TITLE
[BUG] spider.search_news 失效

### ISSUE THREAD

**Issue by JohnWHYH** [BaiduSpider/BaiduSpider#35]
datas=spider.search_news(query=input('资讯搜索关键词：'))
print(datas)

output:
资讯搜索关键词：美国
WARNING: An error occurred while executing function ., which is currently ignored. However, the rest of the parsing process is still being executed normally. This is most likely an inner parse failure of BaiduSpider. For more details, please set the environment variable `DEBUG` to `1` to see the error trace and open up a new issue at https://github.com/BaiduSpider/BaiduSpider/issues/new?assignees=&labels=bug%2C+help+wanted&template=bug_report.md&title=%5BBUG%5D.
{'results': [], 'total': 0}

简单测试了一下：问题在
def search_news(self, query: str, pn: int = 1) -> dict: 
       result = self.parser.parse_news(code)

parse_news   格式化内容，没有提取到，最近百度有更新，建议修改一下提取

**Comment by JohnWHYH** [comment]
页面逻辑变化了

**Comment by samzhangjy** [comment]
您好。这个问题已经在开发版中修复，请切换到dev分支并按照readme进行手动安装。谢谢！

Sam Zhang

________________________________
