### ISSUE TITLE
可不可以录制一个使用视频教程，这样新手也可以知道怎么用

### ISSUE THREAD

**Issue by sankeyou123** [BaiduSpider/BaiduSpider#4]
新手不知道安装什么程序，或者安装后不知道怎么使用，可不可以录制一个视频或者图文教程，帮助大家怎么使用呢

**Comment by sankeyou123** [comment]
没有看懂 是怎么用浏览器访问这个程序的 能帮助一下么

**Comment by samzhangjy** [comment]
这个不是利用浏览器访问的，而是利用爬虫模拟浏览器发送请求给百度，需要安装Python3.6+

**Comment by sankeyou123** [comment]
BaiduSpider.now.sh  视频中访问了这个域名，这个不是程序提供的API么  这个应该怎么实现呢

**Comment by samzhangjy** [comment]
可以查看组织BaiduSpider下的BaiduSpider-web查看源码

**Comment by sankeyou123** [comment]
网页版能不能 付费帮我实现呢 教程我没看懂呢

**Comment by samzhangjy** [comment]
源码已经在GitHub上面了啊

**Comment by sankeyou123** [comment]
BaiduSpider-web 源码能在上传一下么  没有了

**Comment by samzhangjy** [comment]
代码就在repo

**Comment by samzhangjy** [comment]
抱歉，刚才不小心给关了，网页版的代码就在[repo](https://github.com/BaiduSpider/BaiduSpider-web)里面，使用Vue搭建，直接clone就可以

**Comment by samzhangjy** [comment]
目前还没有QQ群，有问题可以发我邮箱：samzhang951@outlook.com
