### ISSUE TITLE
结果导出

### ISSUE THREAD

**Issue by 783993130** [BaiduSpider/BaiduSpider#48]
项目能实现爬虫结果导出么？或者您可以提供给我一些结果导出的建议么？

**Comment by samzhangjy** [comment]
您可以使用`.plain`参数获取结果字典，然后使用`json`库转存为`JSON`文件。

**Comment by 783993130** [comment]
现在.plain的输出结果是list吧，那我把他变成dict，直接导入数据库应该也可以吧
