### ISSUE TITLE
[BUG]描述明明是存在的，确显示为空

### ISSUE THREAD

**Issue by ganjunhong** [BaiduSpider/BaiduSpider#49]
我是输入这个标题：绿灯间隔时间名词解释
百度的搜索结果是有的
但是代码返回的描述，除了第一个，其他的都为空

**Comment by samzhangjy** [comment]
抱歉，我最近学业比较繁忙（OIer，马上要比赛了），来不及维护……请谅解

**Comment by samzhangjy** [comment]
您好，我这边所有描述均存在。请尝试设置cookie后重试。
