### ISSUE TITLE
[BUG]requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

### ISSUE THREAD

**Issue by chenjun0210** [BaiduSpider/BaiduSpider#5]
爬取百度知道时报错，是不是被禁了。

**Comment by samzhangjy** [comment]
这个报错应该是无法请求到服务器，请提供详细代码。

**Comment by chenjun0210** [comment]
就是用的您这边提供的search_zhidao这个接口，里面的解析title，time的我改了一下，之前的有些解析报错。刚开始跑能够取到数据，差不多爬了几十条数据后，就报这个错误。。

**Comment by chenjun0210** [comment]
网上搜索了一下，可能是requests中header设置问题，我试试看。

**Comment by chenjun0210** [comment]
试了还是不行。。。批量爬取百度知道的搜索结果就不行了貌似。。。。

**Comment by samzhangjy** [comment]
那么这个很有可能就是百度封锁了你的IP对于百度知道的访问。添加代理IP即可解决该问题。
