### ISSUE TITLE
[BUG]当我使用search_news不停地出现如下错误

### ISSUE THREAD

**Issue by ShinCYZhou** [BaiduSpider/BaiduSpider#50]
**描述该问题**

我使用search_news不停地出现KeyError: 'total'的错误。可是需要爬取的单词可以在百度新闻处找到结果。也尝试了加cookie，在爬取五六个词之后很长一段时间都只报这个错误，我爬的数据非常少，每个词至多只爬20条数据，可是加上sleep都没有用。

**复现该问题**

 File "", line 58, in spyder
    baidu = BaiduSpider().search_news(i, show='media', pn=p)
  File "=", line 787, in search_news
    pages = self._calc_pages(result["total"], self.RESULTS_PER_PAGE["news"])
KeyError: 'total'

**预期结果**

希望知道为什么出现这样的错误，如何解决

**系统**

- 操作系统: 例如：windows
- Python版本: 例如：3.6

**Comment by charlven** [comment]
+1

**Comment by charlven** [comment]
+1...
我第一次执行就直接这样了，一条记录都没有出来。
`WARNING: An error occurred while executing function BaiduSpider.parse-web, which is currently ignored. However, the rest of the parsing process is still being executed normally. This is most likely an inner parse failure of BaiduSpider. For more details, please set the environment variable `DEBUG` to `1` to see the error trace and open up a new issue at https://github.com/BaiduSpider/BaiduSpider/issues/new?assignees=&labels=bug%2C+help+wanted&template=bug_report.md&title=%5BBUG%5D.[0m
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\gitRepertories\BaiduSpider\baiduspider\__init__.py", line 458, in search_web
    pages = self._calc_pages(results["total"], self.RESULTS_PER_PAGE["web"])`

**Comment by samzhangjy** [comment]
抱歉，我最近着实有点忙（OIer，马上要比赛了），来不及维护……

**Comment by samzhangjy** [comment]
@ShinCYZhou @charlven 请问您使用的搜索词是什么？我这边暂时没有相关报错。谢谢！
