### ISSUE TITLE
[BUG]运行示例代码没有返回结果

### ISSUE THREAD

**Issue by Y2hlbg-c** [BaiduSpider/BaiduSpider#51]
python版本3.8.6
---
```
from pprint import pprint
from baiduspider import BaiduSpider

result = BaiduSpider().search_web("python",pn=1)
print(result)  # print
print('\n\n')
pprint(result)
```
返回值
![image](https://user-images.githubusercontent.com/81803574/131104314-e0ebd918-3ebd-45c3-ae74-e0aaab07577e.png)

**Comment by php-macoo** [comment]
# 搜索网页
pprint(spider.search_web(query='特斯拉').plain) 

末尾加个「.plain」 改一下就有了。。

**Comment by php-macoo** [comment]
pprint(spider.search_web(query='特斯拉').plain)

末尾加个「.plain」 改一下就有了。。

**Comment by samzhangjy** [comment]
抱歉，我最近学业比较繁忙（OIer，马上要比赛了），来不及维护……请谅解

**Comment by samzhangjy** [comment]
此issue已完结。以后不是bug的请到discussions去提问，谢谢。
