### ISSUE TITLE
[BUG]文库搜索不了

### ISSUE THREAD

**Issue by momingL** [BaiduSpider/BaiduSpider#53]
**描述该问题**

一个对该问题的清晰的描述。

**复现该问题**

请提供能够复现该问题的代码或步骤。

**预期结果**

一个对你想要的结果的清晰的描述。

**实际结果**

你实际得到的结果。

**系统**

- 操作系统: 例如：MacOS
- Python版本: 例如：3.8

**其他描述**

一些关于问题的其他的描述。

**Comment by samzhangjy** [comment]
抱歉，我最近学业比较繁忙（OIer，马上要比赛了），来不及维护……请谅解

**Comment by samzhangjy** [comment]
请提供相应报错信息。
