### ISSUE TITLE
[BUG]search_video搜索汉字，比如‘傈僳’时，搜索结果内没有包含这两个字

### ISSUE THREAD

**Issue by yuxing007** [BaiduSpider/BaiduSpider#6]
**pprint(spider.search_video(query=input('视频搜索关键词：')))**

执行上述代码后，在命令行后输入‘傈僳’两个字时，查询出的结果内没有‘傈僳’这连个字。

![image](https://user-images.githubusercontent.com/35390464/100180784-e783f100-2f13-11eb-8b0f-a25315bd2921.png)

我用的就是下面的代码：
`from baiduspider import BaiduSpider
from pprint import pprint

spider = BaiduSpider()

`# 搜索视频`
pprint(spider.search_video(query=input('视频搜索关键词：')))`

**系统**

- 操作系统: Windows10 64位
- Python版本: anaconda3 Python 3.7

**Comment by samzhangjy** [comment]
您好！该问题已经在最近的commit中修复，并已经上传到了PyPI，请重新下载BaiduSpider再试。

**Comment by yuxing007** [comment]
![QQ截图20201125234257](https://user-images.githubusercontent.com/35390464/100250056-35324500-2f78-11eb-9589-0c03bf786d0e.png)
![百度视频傈僳截图](https://user-images.githubusercontent.com/35390464/100250070-395e6280-2f78-11eb-8310-2bb4e9d65292.png)
不好意思，我这边用两种方式下载执行了最新的代码版本，还是和我用百度视频网站搜索的结果不一样呢，新代码的搜索结果中还是没有‘傈僳’这两个字（因为正好在做关于傈僳族的一个网站，所以比较执着于搜索这两个字），麻烦您那边也搜索一下‘傈僳’作为测试，谢谢！

**Comment by samzhangjy** [comment]
好的，我今天会尽快修复，感谢提出！

Sam Zhang

________________________________

**Comment by samzhangjy** [comment]
您好，我今天又重新尝试了一下，用最新版的BaiduSpider代码运行无误，可以出现正常的搜索关键字。我又查看了一下PyPI，目前可以下载的版本还是0.0.3，但是最新版是0.0.4，可以用git下载尝试一下（注意clone最近的commit）。

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by yuxing007** [comment]
不好意思，您的确是已经解决了，我这边自作主张，用单引号把傈僳包括了起来进行搜索：‘傈僳’，再去掉单引号后，就得到正常的搜索结果了，非常感谢，麻烦大神了！
