### ISSUE TITLE
[BUG] 运行示例代码报错

### ISSUE THREAD

**Issue by XiaTiaoQAQ** [BaiduSpider/BaiduSpider#61]
**描述该问题**

代码示例:

from baiduspider import BaiduSpider
from pprint import pprint
spider = BaiduSpider()
pprint(spider.search_web(query='Python'))

**预期结果**

返回搜索结果

**实际结果**

![图片](https://user-images.githubusercontent.com/52430515/142129920-9ca40495-8045-4190-b1f6-77a1b3c2612c.png)

**系统**

- 操作系统: MacOS
- Python版本: 3.8.5

**Comment by Inighty** [comment]
暂时可以先自己下载源码 baiduspider/parser/__init__.py 
35行位置 class修改一下名字
`        num = int(
            str(soup.find("span", class_="hint_PIwZX").text)
            .strip("百度为您找到相关结果约")
            .strip("个")
            .replace(",", "")
        )`

**Comment by samzhangjy** [comment]
您好。此问题已经在最新commit中修复。
