### ISSUE TITLE
[BUG]UnboundLocalError: local variable 'results' referenced before assignment

### ISSUE THREAD

**Issue by 1113971699** [BaiduSpider/BaiduSpider#64]
**描述该问题**

一个对该问题的清晰的描述。

**复现该问题**

请提供能够复现该问题的代码或步骤。

**预期结果**

一个对你想要的结果的清晰的描述。

**实际结果**

你实际得到的结果。

**系统**

- 操作系统: 例如：MacOS
- Python版本: 例如：3.8

**其他描述**

一些关于问题的其他的描述。

**Comment by hebiao6446** [comment]
Traceback (most recent call last):
  File "/Users/admin/PycharmProjects/test/test_test.py", line 23, in <module>
    result = BaiduSpider().search_web('Python')
  File "/Users/admin/PycharmProjects/test/venv/lib/python3.9/site-packages/baiduspider/__init__.py", line 458, in search_web
    pages = self._calc_pages(results["total"], self.RESULTS_PER_PAGE["web"])
UnboundLocalError: local variable 'results' referenced before assignment
WARNING: An error occurred while executing function BaiduSpider.parse-web, which is currently ignored. However, the rest of the parsing process is still being executed normally. This is most likely an inner parse failure of BaiduSpider. For more details, please set the environment variable `DEBUG` to `1` to see the error trace and open up a new issue at https://github.com/BaiduSpider/BaiduSpider/issues/new?assignees=&labels=bug%2C+help+wanted&template=bug_report.md&title=%5BBUG%5D.

**Comment by samzhangjy** [comment]
您好。此问题已经在最新commit中修复。
