### ISSUE TITLE
m.baidu.com 移动端搜索支持

### ISSUE THREAD

**Issue by infosecspace** [BaiduSpider/BaiduSpider#7]
希望能支持移动端搜索
例：https://m.baidu.com/s?word=python

**Comment by samzhangjy** [comment]
这个已经在日程上，但是由于时间原因，可能近期无法实现（目前主要目标是把普通搜索（尤其是网页搜索）做完善）。敬请期待……

**Comment by samzhangjy** [comment]
BaiduSpider v1.0 发布，请更新BaiduSpider到最新版本！
