### ISSUE TITLE
[BUG]AttributeError: 'NoneType' object has no attribute 'findAll'

### ISSUE THREAD

**Issue by nutshell999** [BaiduSpider/BaiduSpider#8]
**描述该问题**

使用新闻搜索爬取关键词，出现上诉情况

**复现该问题**

from baiduspider import BaiduSpider
from pprint import pprint

res = BaiduSpider().search_news('粤港澳大湾区')
count = res['total']
all=100;
page = 1;

**预期结果**

目标新闻res

**实际结果**

报错

**系统**

- 操作系统: 例如：MacOS
- Python版本: 例如：3.8

**其他描述**

一些关于问题的其他的描述。

**Comment by gz-sky** [comment]
怎么解决的呢

**Comment by samzhangjy** [comment]
我无法复现该问题。请提供详细的HTML代码。

**Comment by yongliu1992** [comment]
我从全新安装 python3 和3.7 都是这样
from baiduspider import BaiduSpider  # 导入BaiduSpider
from pprint import pprint  # 导入pretty-print

# 获取百度的搜索结果，搜索关键词是'爬虫'
pprint(BaiduSpider().search_web('爬虫'))
报错了

(untitled) ➜  untitled python3 main.py         
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    pprint(BaiduSpider().search_web('爬虫'))
  File "/Users/kok/PycharmProjects/untitled/lib/python3.7/site-packages/baiduspider/__init__.py", line 196, in search_web
    self._handle_error(error)
  File "/Users/kok/PycharmProjects/untitled/lib/python3.7/site-packages/baiduspider/_spider.py", line 71, in _handle_error
    raise error
baiduspider.errors.UnknownError: 'NoneType' object has no attribute 'find'

**Comment by Edgaraaa** [comment]
表示同样问题，之后自己访问了一波百度。发现自己被ban了

**Comment by samzhangjy** [comment]
目前在最新版本`V0.0.7`已经修复该问题。由于百度近期频繁更改界面细节，可能会导致爬虫不稳定。此外，本项目已经声明，不可使用本爬虫爬取大量信息。BaiduSpider也不会提供相对应的解决方案，特此说明，请谅解。
