### ISSUE TITLE
[BUG]连续多次搜索后报错KeyError: 'total'

### ISSUE THREAD

**Issue by MengxinWu** [BaiduSpider/BaiduSpider#88]
**描述该问题**

连续多次搜索后报错KeyError: 'total'

**复现该问题**

>>> from baiduspider import BaiduSpider
>>> result = BaiduSpider().search_web('Python', exclude=["tieba", "baike"])

**预期结果**
>>> from baiduspider import BaiduSpider
>>> result = BaiduSpider().search_web('Python', exclude=["tieba", "baike"])
>>> result.plain
[{'title': 'Welcome to Python.org', 'des': 'The official home of the Python Programming Language', 'origin': 'www.python.org/', 'url': 'http://www.baidu.com/link?url=GDThJSZas_pwwrf4DrH3KFh_YoHaoqTNX6qoBGk9Ged0WKYVo_jULTxPYWCxs6n9', 'time': None, 'type': 'result'}, {'title': '下载和安装 python - Download Python | Python.org', 'des': 'The official home of the Python Programming Language', 'origin': 'www.python.org/getit/', 'url': 'http://www.baidu.com/link?url=2j7ljbFGKNKnXNMdsEqyKywXoroZfMtWWI-YeI-bZjs5z0tifD3hR9dqfagRfceW', 'time': '2021年10月4日', 'type': 'result'}, {'title': 'Python 基础教程 | 菜鸟教程', 'des': '/usr/bin/python的解释,相信很多不熟悉 Linux 系统的同学需要普及这个知识,脚本语言的第一行,只对 Linux/Unix 用户适用,用来指定本脚本用什么解释器来执行。 有这句的,加上执行权限后...', 'origin': 'www.runoob.com/python/python-t...', 'url': 'http://www.baidu.com/link?url=qnW2ykMn2V5BLlkwDGeeoLKIY94ritYVSJvrQBepTSrzGC-o3zmT-RGYtZ03V-ImbLullpPOdJVS5FWCvuZ6qa', 'time': '2020年1月1日', 'type': 'result'}, {'title': 'Python教程 - 廖雪峰的官方网站', 'des': '中文,免费,零起点,完整示例,基于最新的Python 3版本。 Python是一种计算机程序设计语言。你可能已经听说过很多种流行的编程语言,比如非常难学的C语言,非常流行的Java语言,适合初学者的Basic语言,...', 'origin': 'www.liaoxuefeng.com/wiki/10169...', 'url': 'http://www.baidu.com/link?url=0EA9kRmbscstDMVQcHCZCabi4cvske-gXfadYjhO2sEDuxueHEBEmuGw5HZn0-zC_bXOP8qE9vvzhwqxUhytU_', 'time': None, 'type': 'result'}, {'title': '你都用 Python 来做什么? - 知乎', 'des': '发现很多人都在学习 Python ,但是没有明确的说明可以做什么,主流的功能是什么?想知道目前利用 Python 开发的都在干什么? 关注者38,147 被浏览11,484,439 关注问题\u200b写回答 \u200b邀请回...', 'origin': '知乎', 'url': 'http://www.baidu.com/link?url=oKOE6ayTgW-BSh4iUlZnkcwTs_WgoZm8ON-AlN1onNg5pvpwrWyXRPTMP9qKWr1I5_ai1Uxp11eXq8CSq4YRBK', 'time': '2019年10月17日', 'type': 'result'}]

**实际结果**
>>> from baiduspider import BaiduSpider
>>> result = BaiduSpider().search_web('Python', exclude=["tieba", "baike"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/baiduspider/__init__.py", line 453, in search_web
    pages = self._calc_pages(results["total"], self.RESULTS_PER_PAGE["web"])
KeyError: 'total'

**系统**

- 操作系统: Ubuntu
- Python版本: Python 3.8.0
- BaiduSpider 版本： 1.0.1.1

**其他描述**

连续多次调用正常后开始一直报错。

**Comment by samzhangjy** [comment]
@MengxinWu 您好。我在我这边测试没有问题，请问您之前是否进行了大量爬取呢（100条+）？

**Comment by MengxinWu** [comment]
不一定有100次，大几十次吧，我是搜一篇文章的每句话，前面都正常输出，突然就开始报错了，是不是百度搜索有限制？感谢您及时回复。

**Comment by samzhangjy** [comment]
您好。我刚刚修复了这个bug，请您下载最新版（1.0.1.2）后重试。
