### ISSUE TITLE
[BUG] linux Python3.6.9 使用spider.search_wenku('key') 报错： Traceback (most recent call last):   File "<stdin>", line 1, in <module>   File "/home/dbachen/BaiduSpider/baiduspider/__init__.py", line 585, in search_wenku     pages_ = bs.find('div', class_='page-content').findAll('a') AttributeError: 'NoneType' object has no attribute 'findAll'

### ISSUE THREAD

**Issue by HectorJi** [BaiduSpider/BaiduSpider#9]
**描述该问题**

一个对该问题的清晰的描述。

**复现该问题**

请提供能够复现该问题的代码或步骤。

**预期结果**

一个对你想要的结果的清晰的描述。

**实际结果**

你实际得到的结果。

**系统**

- 操作系统: 例如：MacOS
- Python版本: 例如：3.8

**其他描述**

一些关于问题的其他的描述。

**Comment by samzhangjy** [comment]
您好，由于百度安全验证原因，BaiduSpider无法直接获取网页。请手动打开百度文库搜索（链接：https://wenku.baidu.com/search/main?pv=search&word=key&lm=0&od=0&fr=top_home&ie=utf-8&url=/search?word=key&lm=0&od=0&fr=top_home&ie=utf-8）并验证后（仅需1次），BaiduSpider方可进行正常搜索。
