### ISSUE TITLE
[BUG]百度搜索内容为空时程序报错

### ISSUE THREAD

**Issue by MengxinWu** [BaiduSpider/BaiduSpider#91]
**描述该问题**

直接百度搜索返回结果为空时，程序运行报错。
**复现该问题**

>>> from baiduspider import BaiduSpider
>>> result = BaiduSpider().search_web('这格瓦拉还算有义气，收了钱肯办事儿。', exclude=["tieba", "baike"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/baiduspider/__init__.py", line 453, in search_web
    pages = self._calc_pages(results["total"], self.RESULTS_PER_PAGE["web"])
KeyError: 'total'

**预期结果**

>>> result = BaiduSpider().search_web('这格瓦拉还算有义气', exclude=["tieba", "baike"])
>>> result.plain
[{'title': '窃·格瓦拉为什么说里面个个人才,说话又好听? - 哔哩哔哩', 'des': '还有300家机构,拿着真金白银要和窃格瓦拉签约。 进监狱前,窃格瓦拉说里面个个都是人才,说话又好听,超喜欢在里面。 为流行文化研究带师,我们不可能不对监狱文化有所涉猎。那么监狱里...', 'origin': '哔哩哔哩', 'url': 'http://www.baidu.com/link?url=dN6rXnP5kpBABzs8UQYKwMuXWQvAUWN2pvf24vlm9YXudhnK8PdnICn2QoxuW9UWy7fyTs7GLlJKStUZIq3DAK', 'time': '2020年4月22日', 'type': 'result'}, {'title': '切·格瓦拉真值得一些人如此崇拜吗? - 知乎', 'des': '他够义气：他仅凭一腔热血和对卡斯特罗革命的认同，就能奋不顾身参加未知战斗；他与挚友卡米洛西恩福格斯...', 'origin': '知乎', 'url': 'http://www.baidu.com/link?url=Cjfv9VL1wGG_Zb0JYaSkU1PqouzeKpAjrYnseXB-Tu3kWGbhtQ8d_IgB00TfkbPQRib05DhSpJrAWRAoeRw8QExDs-T6qcnG62rDLMMKDpy', 'time': '2016年11月29日', 'type': 'result'}, {'title': '精神领袖“窃·格瓦拉”首度公开道歉,这几句话令人深思!', 'des': '当年所谓的江湖精神,就是能为弟兄们做些讲“义气”的事,这也是融入这个圈子所必须遵从的生存理念。正如他在视频直播所说,现在只想在家种地,照顾好父母,也许这也是他为追求“自我的自...', 'origin': '弥涅耳瓦的猫头鹰', 'url': 'http://www.baidu.com/link?url=UqWCugy4ZBY5iz1EsCmWAnSl8LYQe0tB8BKPpk2U5ae6NKt07_7NYACs2ot8poGA-BYFNHMuOY5m6f_wEpaKbAn8YhZQIo9CLd36O07Jpgy', 'time': '2020年6月5日', 'type': 'result'}, {'title': '说实话我不太喜欢窃格瓦拉这人,感觉没什么人性 - 虎扑社区', 'des': '既然傻逼主播这种都有人喜欢，觉得切格瓦拉说话有意思也没什么可喷的吧，至少切格瓦拉是说自己真实想法的...', 'origin': 'bbs.hupu.com/341681...html', 'url': 'http://www.baidu.com/link?url=_cHK4cW-bHsmpF-YWJSAK2KOHdijK276rxvjkYyv0RU2Ev9xl15osQCxYxYTkCAB', 'time': '2020年4月12日', 'type': 'result'}, {'title': '为什么窃格瓦拉会那么受到崇拜?【历史吧】 - 百度贴吧', 'des': '为什么窃格瓦拉会那么..一方面,窃身上充满了理想的光辉,2012年接受采访之后继续偷电车,抓了放放了偷,从没有去打过工,用自己的名气赚钱,这就像切从来没有放弃理...', 'origin': '百度贴吧', 'url': 'http://www.baidu.com/link?url=TUqICG81hMifYA4O1KSUtBn5i_g2iEYuMkZYs-apsmYSUEIRlSdVZZvmXGnFm_NX', 'time': '2018年9月25日', 'type': 'result'}, {'title': '如何评价窃·格瓦拉? - 哔哩哔哩', 'des': '窃·格瓦拉,原名周立齐,绰号“阿三”,男,1984年12月27日出生于广西壮族自治区南宁市,壮族,小学文化,无业,户籍所在地南宁市兴宁区。 入刑记录 于2007年6月4日因...', 'origin': '哔哩哔哩', 'url': 'http://www.baidu.com/link?url=6s7_NW3BzrUBdq7a1xuIAXA4OBihIakbyhN6X9rQgERRB3ZWFwHQBDLmmLNgUsgqOhrDo6Eoe-GjoINYve1sxK', 'time': '2020年4月12日', 'type': 'result'}, {'title': '重新做人的“窃格瓦拉”,为什么不能当网红?', 'des': '窃格瓦拉也是媒体的“宠儿”。早在三月底四月初,就有众多自媒体报道“窃格瓦拉即将出狱”,像是为其“归来”造势一样。4月18日当天,有关他的报道铺天盖般出现在各大互联网平台,“这辈...', 'origin': '暮雨潇潇dfhdkf', 'url': 'http://www.baidu.com/link?url=EE1w9he2-rX_Ii1s7DOTMLZAvzyQnGV_1ur-zYsygU6yFS-M10IIspX7bw1h-H5ZeIjj_rCLaggcEzCDufnlFM8d0byY1cntBtNcNc-cFaa', 'time': '2020年4月24日', 'type': 'result'}, {'title': '切·格瓦拉真值得一些人如此崇拜吗 - 百度知道', 'des': '最佳答案: 他够义气：他仅凭一腔热血和对卡斯特罗革命的认同，就能奋不顾身参加未知战斗；他与挚友卡米洛西恩福格斯情同手足，甚至将自己儿子的取名卡米罗以缅怀逝去的朋友；...更多关于这格瓦拉还算有义气的问题>>', 'origin': '百度知道', 'url': 'http://www.baidu.com/link?url=d_esFLv8lv-8TBe1wY1lzPbaHMwnj2CkPb0Em_SUviWfeCRSjtf_X-Xp9kOH0Z19Dibq1KEZBzaWhXff_gwSEuEoK3-j1kqGkXJVWYmPdka', 'time': None, 'type': 'result'}, {'title': '如何评价切·格瓦拉与卡斯特罗? - 知乎', 'des': '在墨西哥城，卡斯特罗遇到了切·格瓦拉。他们二人一见如故，结下了深厚的革命友谊，对卡斯特罗来说，切既...', 'origin': '知乎', 'url': 'http://www.baidu.com/link?url=b9yoYMmJ3n0Vn11SNEl9XETa4VcMoKsFlRTZ3JCu7Y2F4whpDH2zMiOMgO5eEc_FlujXnKQGMUdpoxLKYfNqZ_', 'time': '2016年11月25日', 'type': 'result'}, {'title': '为什么我们想“躺平”?|窃·格瓦拉|切·格瓦拉', 'des': '家境贫苦,小时候经常光脚上学,而接受正规教育止于小学,曾北上打过工,也谈过一个漂亮的女朋友。在年近五旬的大姐眼里,窃·格瓦拉对朋友讲义气,人也善良,“那时年...', 'origin': '腾讯网', 'url': 'http://www.baidu.com/link?url=cUYtNmwMzSKkZWLR1xIVxjLgALvWTBDQOJ82JMrp8lzrJtmJzW3l-e2m7sp33TwUve8bg6IMYODFWPm4OUNR2a', 'time': '2021年6月1日', 'type': 'result'}]
![image](https://user-images.githubusercontent.com/26430804/147066713-85748175-5ec1-4f59-b09b-d415ea36af8a.png)

**实际结果**

>>> result = BaiduSpider().search_web('这格瓦拉还算有义气，收了钱肯办事儿。', exclude=["tieba", "baike"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/baiduspider/__init__.py", line 453, in search_web
    pages = self._calc_pages(results["total"], self.RESULTS_PER_PAGE["web"])
KeyError: 'total'
![image](https://user-images.githubusercontent.com/26430804/147066794-60f8b301-edd1-46f9-b324-3324a73d0552.png)

**系统**

- 操作系统: MacOS
- Python版本: 3.8
- 版本：BaiduSpider  1.0.1.2

**其他描述**

百度网页搜索返回空的时候，程序搜索为空。

**Comment by samzhangjy** [comment]
此问题已修复，请重新下载。
