### ISSUE TITLE
[BUG]在搜索结果为空时, 报找不到"total"键

### ISSUE THREAD

**Issue by Goldensoap** [BaiduSpider/BaiduSpider#92]
**描述该问题**

在#91中出现的问题,并没有得到真正修复 . [报错产生的原因在baiduspider->parser文件夹->init.py->Parser类->parse_web函数
```
#__init__.py文件31行32行
  if soup.find("div", id="content_left") is None:
     return {"results": [], "pages": 0}
```

因为搜索结果为空返回的解析结果中不包含id为content_left的div . 所以这里会直接返回空集. 
在上层调用(位于baiduspider->__init__.py 453行因为索引 total而报错)
`pages = self._calc_pages(results["total"], self.RESULTS_PER_PAGE["web"])`
**复现该问题**

通过代码或者百度网页 , 输入随便什么, 通过搜索工具限制时间, 达到无结果页面, 可以在F12 或 BS4 解析结果内看到没有相关div

**系统**

- 操作系统: ubuntu20.04
- Python版本: 例如：3.9
- 库版本:1.0.1.3

**Comment by Goldensoap** [comment]
我已提交PR，尝试修复这个问题

**Comment by samzhangjy** [comment]
感谢您提交PR！已经merge到主分支上。
