### ISSUE TITLE
[BUG]related获取不到

### ISSUE THREAD

**Issue by photkey** [BaiduSpider/BaiduSpider#94]
**描述该问题**

related返回的应该是“相关搜索”的关键词吧？如果是的话 返回结果始终是空列表，手动搜索实际是有相关搜索词的。

**复现该问题**

```
from baiduspider import BaiduSpider
from pprint import pprint


spider = BaiduSpider()
s = spider.search_web(query='SEO').related
pprint(s)
```

![Snipaste_2021-12-24_04-43-44](https://user-images.githubusercontent.com/60434581/147289979-d927df90-24e6-4dfa-a2e4-91a544813e56.png)

**系统**

- 操作系统: Win11
- Python版本: 3.9.7

**Comment by photkey** [comment]
看了一下源码，好像不是`related`不是我想的“**相关搜索**”，我截图中的“相关搜索”的关键词，不考虑加到采集功能里面吗？

**Comment by samzhangjy** [comment]
您好，`related` 应当返回相关搜索结果，这可能是一个bug，我一会会尝试修复

**Comment by samzhangjy** [comment]
Issue fixed by commit [dab5a9d](https://github.com/BaiduSpider/BaiduSpider/commit/dab5a9dca57786b02a179ba8a191dba8df7579e0).
